name: Weekly Rate Tracker
on:
  schedule:
    - cron: "5 8 * * 1"     # Mondays 08:05 UTC
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run scraper
        run: node index.js
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          CHECKIN_OFFSET_DAYS: 7
          NIGHTS: 2
